apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f in2/docker-compose-soafee.yml -o out2/
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: end-node
  name: end-node
spec:
  clusterIP: 10.43.134.3
  ports:
    - name: enode-doip-svc
      port: 13400
      targetPort: enode-doip-port
  selector:
    io.kompose.service: end-node
