apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f in2/docker-compose-soafee.yml -o out2/
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: esync-client
  name: esync-client
spec:
  clusterIP: 10.43.134.2
  ports:
    - name: ssh-srv-svc
      port: 30022
      targetPort: ssh-srv-port
      nodePort: 30022
    - name: esync-bus-svc
      port: 9133
      targetPort: esync-bus-port
      nodePort: 31933
    - name: esclt-doip-svc
      port: 13400
      targetPort: esclt-doip-port
      nodePort: 31340
  type: LoadBalancer
  selector:
    io.kompose.service: esync-client
status:
  loadBalancer: {}
