apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f in/docker-compose-soafee.yml -o out
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: esync-client
  name: esync-client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: esync-client
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f in/docker-compose-soafee.yml -o out
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: esync-client
    spec:
      containers:
        - image: gitlab.excelfore.com:4444/xl4-devops/deployment/customer/soafee-japan/esync-client:latest
          name: esync-client
          ports:
            - containerPort: 22
              name: ssh-srv-port
            - containerPort: 9133
              name: esync-bus-port
            - containerPort: 13400
              name: esclt-doip-port
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: esync-client-priv
              subPath: data
            - mountPath: /root/scripts
              name: esync-client-priv
              subPath: scripts
            - mountPath: /root/.ssh-priv
              name: esync-client-priv
              subPath: ssh-priv
      hostname: esync-client
      restartPolicy: Always
      volumes:
        - name: esync-client-priv
          persistentVolumeClaim:
            claimName: esync-client-pvc
status: {}
